spring:
  application:
    name:regesc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdata_jpa?useTimezone=true&serverTimezone=UTC
    username: root
    password: passwordHere
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
##      hibernate:
##        dialect: org.hibernate.dialect.MySQLDialect
    show_sql: false
    open-in-view: false # vai sumir o WARN de spring.jpa.open-in-view
logging:
  level:
    root: WARN

